version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_USERNAME=kbwecvobzovsel
#      - SPRING_DATASOURCE_PASSWORD=e9cccf032f934b10fda97f7fc39db84a0eb1b0ff4e43855273967a574d58e19c
